django/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webtoon.urls'))
]

django/webtoon/urls.py
from django.urls import path
from . import views

app_name = 'webtoon'
urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.webtoon_list, name='webtoon-list'),
    path('detail/<int:pk>/', views.webtoon_detail, name='webtoon-detail'),
    path('search/', views.search_list, name='search-list'),
    path('save/<int:webtoon_id>/<str:title>/', views.save_webtoon, name='save-webtoon'),
]

django/webtoon/models.py
from django.db import models
import requests
import re
from bs4 import BeautifulSoup as bs


class Webtoon(models.Model):
    id = models.AutoField(primary_key=True)
    webtoon_id = models.CharField(max_length=200)
    title = models.CharField(max_length=200)

    def get_episode_list(self):
        url = 'http://comic.naver.com/webtoon/list.nhn'
        i = 1
        while True:
            param = {
                'titleId': self.webtoon_id,
                'page': i,
            }
            response = requests.get(url, param)
            soup = bs(response.text, 'lxml')
            tr_list = soup.find('table', class_='viewList').findAll('tr')[1:]

            for tr in tr_list:
                if tr.get('class') and 'band_banner' in tr.get('class'):
                    continue
                p = re.compile(r'no=(.*?)&')
                episode_url = tr.find('td').find('a').get('href')
                episode_id = re.search(p, episode_url).group(1)
                if Episode.objects.filter(webtoon_id=self.pk).filter(episode_id=episode_id).exists():
                    continue
                title = tr.find('td', class_='title').find('a').text
                rating = tr.find('div', class_='rating_type').find('strong').text
                created_date = tr.find('td', class_='num').text
                url_thumbnail = tr.find('td').find('img').get('src')
                Episode.objects.create(
                    episode_id=episode_id,
                    url_thumbnail=url_thumbnail,
                    title=title,
                    rating=rating,
                    created_date=created_date,
                    webtoon_id=self.pk,
                )
            print(f'last epi: {episode_id}')
            print(f'page: {i}')
            if episode_id == '1':
                break
            i += 1


class Episode(models.Model):
    webtoon = models.ForeignKey(Webtoon, on_delete=models.CASCADE)
    episode_id = models.CharField(max_length=200)
    title = models.CharField(max_length=200)
    rating = models.CharField(max_length=200)
    created_date = models.CharField(max_length=200)
    url_thumbnail = models.TextField(default='')

    def __str__(self):
        return f'Episode: {self.webtoon} | {self.title}'

    class Meta:
        ordering = ['-created_date']

django/webtoon/views.py
from django.shortcuts import render, redirect
from .models import Webtoon, Episode
from webtoon import utils


# Create your views here.

def webtoon_list(request):
    webtoons = Webtoon.objects.all()
    context = {
        'webtoons': webtoons,
    }
    return render(request, 'webtoon/webtoon_list.html', context)


def webtoon_detail(request, pk):
    episodes = Episode.objects.filter(webtoon_id=pk)
    context = {
        'episodes': episodes,
    }
    return render(request, 'webtoon/webtoon_detail.html', context)


def index(request):
    return render(request, 'webtoon/index.html')


def search_list(request):
    keyword = request.GET['keyword']
    context = {
        'search_list': utils.search_webtoon(keyword),
    }
    return render(request, 'webtoon/search_list.html', context)


def save_webtoon(request, webtoon_id, title):

    if not Webtoon.objects.filter(webtoon_id=webtoon_id).exists():
        webtoon = Webtoon.objects.create(
            webtoon_id=webtoon_id,
            title=title,
        )
        webtoon.get_episode_list()
        return redirect('webtoon:webtoon-detail', pk=webtoon.pk)
    else:
        toon = Webtoon.objects.get(webtoon_id=webtoon_id)
        print(toon)
        return redirect('webtoon:webtoon-detail', pk=toon.pk)

django/templates/base.html
<!doctype html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/webtoon.css' %}">
</head>
<body>
<div class="header">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webtoon:index' %}">Search</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'webtoon:webtoon-list' %}">Database</a>
        </li>
    </ul>
</div>
<h1 class="center title">{% block title %}{% endblock %}</h1>
<div class="wrapper">
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>

django/templates/webtoon/index.html
{% extends 'base.html' %}

{% block content %}
<div class="logo center">
    <img src="https://t1.daumcdn.net/thumb/R1280x0/?fname=http://t1.daumcdn.net/brunch/service/user/h5b/image/4-cEVqd5T1cINxE7v9hikqUwPPs.png" alt="">
</div>
<div class="center">
    <form action="{% url 'webtoon:search-list' %}" class="" method="get">
        <div class="form-group fz0">
            <input type="text" class="form-control verticalMiddle width60" name="keyword" placeholder="웹툰 제목을 입력해주세요">
            <button type="submit" class="btn btn-primary">검색</button>
        </div>
    </form>
</div>
{% endblock %}

django/templates/webtoon/search_list.html
{% extends 'base.html' %}
{% block title %}검색 결과{% endblock %}
{% block content %}
    <div class="list-group">
    {% if search_list %}
    {% for toon in search_list %}
        <a href="{% url 'webtoon:save-webtoon' webtoon_id=toon.webtoon_id title=toon.title %}" class="list-group-item-action list-group-item">{{ toon.title }}</a>
    {% endfor %}
    {% else %}
        <h2>검색 결과가 없습니다.</h2>
    {% endif %}
    </div>
{% endblock %}

django/templates/webtoon/webtoon_detail.html
{% extends 'base.html' %}

{% block title %}{{ episodes.first.webtoon.title }}{% endblock %}
{% block content %}
<table class="table table-hover">
    <thead>
        <tr>
            <th>이미지</th>
            <th>번호</th>
            <th>제목</th>
            <th>별점</th>
            <th>등록일</th>
        </tr>
    </thead>
    <tbody>
    {% for episode in episodes %}
        <tr>
            <th><img class="img-thumbnail img100" src="{{ episode.url_thumbnail }}"></th>
            <td>{{ episode.episode_id }}</td>
            <td><a href="http://comic.naver.com/webtoon/detail.nhn?titleId={{ episode.webtoon.webtoon_id }}&no={{ episode.episode_id }}">{{ episode.title }}</a></td>
            <td>{{ episode.rating }}</td>
            <td>{{ episode.created_date }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

django/templates/webtoon/webtoon_list.html
{% extends 'base.html' %}

{% block title %}Webtoon list{% endblock %}
{% block content %}
    <div class="list-group">
    {% for webtoon in webtoons %}
        <a href="{% url 'webtoon:webtoon-detail' pk=webtoon.pk %}" class="list-group-item-action list-group-item">{{ webtoon.title }}</a>
    {% endfor %}
    </div>
{% endblock %}